In [20]:
import cifar10
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn import ensemble
import time
from sklearn.metrics import classification_report , confusion_matrix
from sklearn import svm
import numpy as np 

In [2]:
cifar10.data_path = "data/CIFAR-10/"

In [3]:
cifar10.maybe_download_and_extract()

Data has apparently already been downloaded and unpacked.


In [4]:
class_names = cifar10.load_class_names()
class_names

Loading data: data/CIFAR-10/cifar-10-batches-py/batches.meta


['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [6]:
images_train, cls_train, labels_train = cifar10.load_training_data()
images_test, cls_test, labels_test = cifar10.load_test_data()

Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_1
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_2
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_3
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_4
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_5
Loading data: data/CIFAR-10/cifar-10-batches-py/test_batch


In [8]:
x_train = images_train
y_train = cls_train
x_test = images_test
y_test = cls_test

In [9]:
X_TRAIN = x_train.reshape(50000,3072)
X_TRAIN.shape

(50000, 3072)

In [10]:
y_train.shape

(50000,)

In [11]:
X_TEST = x_test.reshape(10000 , 3072)

In [12]:
X_TEST.shape

(10000, 3072)

In [13]:
y_test.shape

(10000,)

In [14]:
pca = PCA()
pca.fit(X_TRAIN)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [15]:
k = 0
total = 0
while total < 0.99:
    total += pca.explained_variance_ratio_[k]
    k = k+1 
k

658

In [16]:
pca_new = PCA(n_components=k , whiten=True)

In [17]:
trans = pca_new.fit_transform(X_TRAIN)
trans.shape

(50000, 658)

In [18]:
x_train_pca = trans 
x_test_pca = pca_new.transform(X_TEST)
print(x_test_pca.shape)
print(x_train_pca.shape)

(10000, 658)
(50000, 658)


In [42]:
rf = ensemble.RandomForestClassifier()
start = time.time()
rf.fit(X_TRAIN,y_train)
print(time.time() - start)
predictions = rf.predict(X_TEST)


25.85056233406067


In [52]:
labels = []
for i in range(len(predictions)):
    labels.append(class_names[predictions[i]])

In [53]:
np.savetxt("111predictions.csv", labels, fmt = '%s')

In [54]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

             precision    recall  f1-score   support

          0       0.38      0.54      0.45      1000
          1       0.36      0.45      0.40      1000
          2       0.25      0.29      0.27      1000
          3       0.22      0.23      0.22      1000
          4       0.30      0.30      0.30      1000
          5       0.33      0.28      0.30      1000
          6       0.39      0.33      0.36      1000
          7       0.43      0.31      0.36      1000
          8       0.53      0.49      0.51      1000
          9       0.44      0.36      0.40      1000

avg / total       0.36      0.36      0.36     10000

[[540  60  63  35  36  26  22  28 138  52]
 [105 449  42  66  31  44  32  37  70 124]
 [139  59 292  98 148  66 105  47  28  18]
 [ 84  79 135 225  84 155 103  57  25  53]
 [ 68  49 217  75 303  53 113  79  24  19]
 [ 71  58 123 197 103 276  52  74  26  20]
 [ 47  60 146 143 153  64 325  30   8  24]
 [ 86  89  91  94 104  88  34 311  28  75]
 [169 111  30  45

In [49]:
rf = ensemble.RandomForestClassifier()
start = time.time()
rf.fit(x_train_pca,y_train)
print(time.time() - start)
y_pred = rf.predict(x_test_pca)


21.436733722686768


In [50]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

             precision    recall  f1-score   support

          0       0.22      0.37      0.27      1000
          1       0.23      0.32      0.27      1000
          2       0.17      0.23      0.19      1000
          3       0.18      0.20      0.19      1000
          4       0.23      0.23      0.23      1000
          5       0.21      0.17      0.19      1000
          6       0.27      0.19      0.22      1000
          7       0.25      0.15      0.19      1000
          8       0.35      0.26      0.30      1000
          9       0.28      0.16      0.21      1000

avg / total       0.24      0.23      0.22     10000

[[368  83 117  70  63  74  28  34 122  41]
 [144 319  63  88  54  55  56  50  65 106]
 [172  76 226  94 166  70  96  42  37  21]
 [127 110 134 196 100 106  74  67  43  43]
 [128  82 209  90 232  60  86  59  31  23]
 [132 100 135 168  91 167  61  61  40  45]
 [ 97 117 152 119 140  79 192  53  24  27]
 [133 111 151 130  97  68  58 150  42  60]
 [236 123  98  85

In [55]:
svm = svm.SVC()

In [ ]:
start = time.time()
svm.fit(x_train_pca,y_train)
print(time.time() - start)

In [ ]:
y_pred = svm.predict(x_test_pca)